// Polyfills
import 'intersection-observer';
import './polyfills/foreach';
import './polyfills/prepend';

// Modules
import './modules/search';
import './modules/table';
import './modules/table-sort';
import './modules/sticky';
import './modules/formfilter';
import './modules/media';
import './modules/pdf';
import './modules/share';
import './modules/lazy-image-loading';
import './modules/anchor';
import './modules/accordion';
import './modules/slideout';
import './modules/slideout-main-menu';
import './modules/carousel';
import './modules/under-menu';
