#!/bin/bash

branch=`git rev-parse --abbrev-ref HEAD`

if [[ $branch =~ release ]] || [[ $branch =~ hotfix ]]; then
  printf "Running version checker...\n"

  branch_version=$(echo "${branch}" | grep -Eo '[[:digit:]]+\.[[:digit:]]+\.[[:digit:]]+')
  version_check=$(awk "/version*(.+)${branch_version}/" package.json)

  if [[ -z "$version_check" ]]; then
      printf "Version Mismatch Error: The package.json version does not match the current branch version.\n"
      exit 1
  fi
fi

exit 1;
