#!/bin/bash

# Run on either wild wayne or local machine
wild_wayne_test=${WILD_WAYNE}

# Current working directory of the site
site_folder=${PWD##*/}

export PATH=/usr/local/bin:$PATH

# Make sure vagrant command is found
if [ "$wild_wayne_test" != "true" ]; then
    if hash vagrant 2>/dev/null; then
        printf "vagrant command found...\n"
    else
        printf "Vagrant command could not be found. If you plan to develop without using vagrant then delete this check.\n"
        exit 1
    fi
fi

# Make sure commits aren't directly going to the master branch
branch=`git rev-parse --abbrev-ref HEAD`

if [[ "$branch" == "master" ]]; then
    printf "You are on branch $branch. Are you sure you want to commit to this branch?\n"
	printf "If so, commit with -n to bypass this pre-commit hook.\n"
    exit 1
fi

# PHP linting
if [ "$wild_wayne_test" = "true" ]; then
    printf "Running phplint...\n"
    phplint="$(make phplintdry)"
else
    printf "Running phplint...\n"
    phplint="$(vagrant ssh -c "cd /vagrant/${site_folder}; make phplintdry")"
fi

# Check if the last command (PHPLint) didn't exit with a 0 success
if  (( $? != 0 )); then
    printf "phplint has reported errors. Please fix them before committing.\n"
    printf ">> run: make phplint\n\n"
    exit 1
fi

# Style linting
if [ "$wild_wayne_test" = "true" ]; then
    printf "Running stylelint...\n"
    stylelint="$(make stylelint)"
else
    printf "Running stylelint...\n"
    stylelint="$(vagrant ssh -c "cd /vagrant/${site_folder}; make stylelint")"
fi

# Check if the last command (Stylelint) didn't exit with a 0 success
if  (( $? != 0 )); then
    printf "Styleint has reported errors. Please fix them before committing.\n"
    printf ">> run: make stylelint\n\n"
    exit 1
fi

# PHP tests
if [ "$wild_wayne_test" = "true" ]; then
    printf "Running tests...\n"
    phpunit="$(phpunit)"
else
    printf "Running tests...\n"
    phpunit="$(vagrant ssh -c "cd /vagrant/${site_folder}; phpunit")"
fi

# Check if the last command (PHPUnit) didn't exit with a 0 success
if  (( $? != 0 )); then
    printf "phpunit tests failed. Please fix them before committing.\n"
    printf ">> run: make runtests\n"
    exit 1
fi

exit 0;
